global class AccountRecords {
  global static List<String> names;
    public AccountRecords()
    {
         names = new List<String>();
    names.add('Xoriant');
    names.add('Breeze');
    names.add('Covalent');
    names.add('Snizer');
    names.add('Global Sys');
    names.add('Thalapattu');
    names.add('Ecofound');
    names.add('Pinacle');
    names.add('Rise');
    names.add('Info Solutions');
        
        
    }

   public static void accountCreation()
   {
        
   }
 
    
}